#!/bin/bash

# journal 0.3
# Copyright 2010 Ben Winston (winsbe01@gmail.com)
# A simple command-line journal tool.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>


journal=~/.journal/journal

# Colour codes
# text reset
C0="\033[0m"
# white bold
C1="\033[37;1m"
# red bold
C2="\033[91;1m"
# green bold
C4="\033[92;1m"
# cyan
C5="\033[96;1m"
# blue
C6="\033[34;1m"

if [ $# -eq 0 ] || [ "$1" = "-u" ]; then
	clear
	tmpfile=/tmp/$(date +%s)
	touch $tmpfile
	printf "[$(date +%Y-%m-%d)] " >> $tmpfile
	printf .$2 >> $tmpfile
	printf "\n@$3 \n" >> $tmpfile 
	$JNEDITOR +3 $tmpfile
	touch ~/.journal/journal
	cat $tmpfile >> $journal
	echo -e "\n~~~~~\n" >> $journal
	rm $tmpfile
	echo "thanks for the update!"

elif [ "$1" = "-h" ]; then
	echo -e "\njn 0.3"
	echo -e "by Ben Winston and hacked by gwyrdh\n"
	echo -e "command: jn [options]\n"
	echo "  -c => browse the journal in colour"
	echo "  -h => brings you to this help screen"
	echo "  -u => update journal S2 is title S3 is tag"
	echo "  -t => find S2 tag"
	echo "  -s => search for S2 string"
	echo -e "  -g => go to S2 line number of search\n"

# print colour journal. thanks @coderofsalvation kanban.bash
elif [ "$1" = "-c" ]; then
		cat $journal | awk '{ 
    a = gensub(/@([a-zA-Z0-9_\.-]+)/,"'$C5'&'$C0'","g")
    a = gensub(/\.([a-zA-Z0-9_\.-]+)/,"'$C4'&'$C0'","g",a)
    a = gensub(/\[([a-zA-Z0-9_\.-]+)\]/,"'$C6'&'$C0'","g",a)
    print a
  }'

elif [ "$1" = "-t" ]; then
	grep --color -n -A 1 -B 1 @$2 $journal
	
elif [ "$1" = "-s" ]; then
	grep --color -n -A 2 -B 1 "$2" $journal
	
elif [ "$1" = "-g" ]; then
	nano +$2 $journal

else
	echo "That's not (currently) an option! Type jn -h for the help screen."
fi
